name: Deploy blog

on:
  push:
    branches:
      - master

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      # - name: Install pnpm
      #   uses: pnpm/action-setup@v2
      #   with:
      #     version: 7

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Deps
        run: npm install

      - name: Build Blog
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: npm run docs:build

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v2
        with:
          # 部署到 gh-pages 分支
          target_branch: gh-pages
          # 部署目录为 VuePress 的默认 输出目录
          build_dir: src/.vuepress/dist
        env:
          # @see https://docs.github.com/cn/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-gitee:
    runs-on: ubuntu-latest
    needs: deploy-gh-pages
    steps:
      # - name: Sync to Gitee
      #   uses: wearerequired/git-mirror-action@master
      #   env:
      #     # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
      #     SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      #   with:
      #     # 注意替换为你 的 GitHub 源仓库地址
      #     source-repo: git@github.com:hecan1020/hecan1020.github.io.git
      #     # 注意替换为你的 Gitee 目标仓库地址
      #     destination-repo: git@gitee.com:hecan1020/hecan1020.git
      - name: Github Branch Gitee
        # You may pin to the exact commit or the version.
        # uses: shanghaobo/github-branch-gitee@3aa5539194f43f238a94abf95ed78c887c665ae9
        uses: shanghaobo/github-branch-gitee@v1.0.0
        with:
          # Github 仓库，例如 username/repo
          github_repo: hecan1020/hecan1020.github.io
          # Github 分支，例如 main
          github_branch: gh-pages
          # Gitee 仓库，例如 username/repo
          gitee_repo: hecan1020/hecan1020
          # Gitee 分支，例如 master
          gitee_branch: gh-pages
          # Gitee 用户名，用于登录。
          username: ${{ secrets.GITEE_USERNAME }}
          # Gitee 密码，用于登录。
          password: ${{ secrets.GITEE_PASSWORD }}
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@v1.4.1
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: ${{ secrets.GITEE_USERNAME }}
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
          gitee-repo: hecan1020/hecan1020
          # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
          branch: gh-pages
